-- public.clients canonical shape: uuid PK, id = SQLite row id for FK sync
SET search_path TO public;

CREATE TABLE IF NOT EXISTS clients (
  uuid              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id                integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  client_code       text UNIQUE NOT NULL,
  client_name       text NOT NULL DEFAULT '',
  business_name     text DEFAULT '',
  mobile            text DEFAULT '',
  alternate_mobile  text DEFAULT '',
  email             text DEFAULT '',
  gstin             text DEFAULT '',
  pan_number        text DEFAULT '',
  billing_address   text DEFAULT '',
  shipping_address  text DEFAULT '',
  client_type       text DEFAULT 'Regular',
  price_category    text DEFAULT '',
  credit_limit      double precision DEFAULT 0,
  payment_terms     text DEFAULT '',
  opening_balance   double precision DEFAULT 0,
  balance_type      text DEFAULT 'DR',
  is_active         integer NOT NULL DEFAULT 1,
  notes             text DEFAULT '',
  sync_status       text DEFAULT 'PENDING',
  sync_version      integer NOT NULL DEFAULT 1,
  is_deleted        integer NOT NULL DEFAULT 0,
  deleted_at        text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  synced_at         text
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_clients_uuid ON public.clients (uuid);
