-- Add company_details, bank_details, and hsn_sac_master tables to Supabase

SET search_path TO public;

-- ==========================================
-- company_details
-- ==========================================
CREATE TABLE IF NOT EXISTS company_details (
    uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    trade_name text NOT NULL,
    address text NOT NULL DEFAULT '',
    phone text NOT NULL DEFAULT '',
    alt_phone text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    gstin text NOT NULL DEFAULT '',
    state text NOT NULL DEFAULT '',
    is_default integer NOT NULL DEFAULT 0,
    is_active integer NOT NULL DEFAULT 1,
    sync_status text DEFAULT 'PENDING',
    sync_version integer DEFAULT 1,
    is_deleted integer DEFAULT 0,
    deleted_at text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    synced_at text,
    created_by_user_uuid uuid,
    updated_by_user_uuid uuid
);

-- ==========================================
-- bank_details
-- ==========================================
CREATE TABLE IF NOT EXISTS bank_details (
    uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    bank_name text NOT NULL,
    account_holder_name text NOT NULL DEFAULT '',
    account_no text NOT NULL DEFAULT '',
    branch_ifsc text NOT NULL DEFAULT '',
    branch_name text NOT NULL DEFAULT '',
    ifsc_code text NOT NULL DEFAULT '',
    is_default integer NOT NULL DEFAULT 0,
    is_active integer NOT NULL DEFAULT 1,
    sync_status text DEFAULT 'PENDING',
    sync_version integer DEFAULT 1,
    is_deleted integer DEFAULT 0,
    deleted_at text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    synced_at text,
    created_by_user_uuid uuid,
    updated_by_user_uuid uuid
);

-- ==========================================
-- hsn_sac_master
-- ==========================================
CREATE TABLE IF NOT EXISTS hsn_sac_master (
    uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    item_type text NOT NULL,
    item_name text NOT NULL DEFAULT '',
    keyword text NOT NULL DEFAULT '',
    code_type text NOT NULL DEFAULT 'HSN',
    hsn_sac text NOT NULL,
    gst_rate double precision NOT NULL DEFAULT 0.18,
    unit_default text,
    description text NOT NULL DEFAULT '',
    is_favorite integer NOT NULL DEFAULT 0,
    is_active integer NOT NULL DEFAULT 1,
    sync_status text DEFAULT 'PENDING',
    sync_version integer DEFAULT 1,
    is_deleted integer DEFAULT 0,
    deleted_at text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    synced_at text,
    created_by_user_uuid uuid,
    updated_by_user_uuid uuid,
    CONSTRAINT hsn_sac_master_type_keyword_unique UNIQUE(item_type, keyword)
);
